[package]
name = "riiman"
version = "0.1.0"
authors = ["Thomas Bell <github.com/bell345>"]
license = "MIT"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = { version = "0.27" }
egui_extras = { version = "0.27", features = ["all_loaders"] }
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1.0"
built = { version = "0.7", features = ["chrono"] }
serde = "1.0"
serde_json = "1.0"

[build-dependencies]
built = { version = "0.7", features = ["chrono", "semver", "git2"] }
